# Default values for wg-easy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: weejewel/wg-easy
  tag: 4
  pullPolicy: IfNotPresent

web:
  # Set password.secretName if you want to set a web password
  # password:
  #   secretName: ""
  service:
    type: ClusterIP
    port: 51821
    externalTrafficPolicy: Local
    annotations: {}

wireguard:
  service:
    type: ClusterIP
    port: 51820
    externalTrafficPolicy: Local
    annotations: {}

  # Wireguard host is required and used when creating client config
  host: ""
  clientAddrRange: 10.8.0.x
  dns: 1.1.1.1
  allowedIps: "0.0.0.0/0, ::/0"
  persistentKeepalive: 0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  hosts:
    - host: chart-example.local
      paths: []
      # - path: /
      #   pathType: Prefix
  # tls:
  #   - hosts:
  #      - chart-example.local

persistence:
  enabled: false
  size: 100Mi
  annotations: {}
  # storageClass: ""
  accessModes:
    - ReadWriteOnce
  subPath: ""

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
