apiVersion: v1
kind: Service
metadata:
  name: {{ include "wg-easy.fullname" . }}-web
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
  annotations:
  {{- range $key, $value := .Values.web.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type }}
{{- if .Values.web.service.clusterIP }}
  clusterIP: {{ .Values.web.service.clusterIP }}
{{- end }}
{{- if .Values.web.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.web.service.loadBalancerIP }}
{{- end }}
{{- if .Values.web.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.web.service.externalTrafficPolicy }}
{{- end }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "wg-easy.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wg-easy.fullname" . }}-wg
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
  annotations:
  {{- range $key, $value := .Values.wireguard.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  type: {{ .Values.wireguard.service.type }}
{{- if .Values.wireguard.service.clusterIP }}
  clusterIP: {{ .Values.wireguard.service.clusterIP }}
{{- end }}
{{- if .Values.wireguard.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.wireguard.service.loadBalancerIP }}
{{- end }}
{{- if .Values.wireguard.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.wireguard.service.externalTrafficPolicy }}
{{- end }}
  ports:
    - port: {{ .Values.wireguard.service.port }}
      targetPort: {{ .Values.wireguard.service.port }}
      protocol: UDP
      name: wireguard
  selector:
    {{- include "wg-easy.selectorLabels" . | nindent 4 }}
