apiVersion: v1
kind: Service
metadata:
  name: {{ include "wg-easy.fullname" . }}-web
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
spec:
{{- if .Values.web.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.web.service.externalTrafficPolicy }}
{{- end }}
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: {{ .Values.web.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "wg-easy.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wg-easy.fullname" . }}-wg
  labels:
    {{- include "wg-easy.labels" . | nindent 4 }}
spec:
{{- if .Values.wireguard.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.wireguard.service.externalTrafficPolicy }}
{{- end }}
  type: {{ .Values.wireguard.service.type }}
  ports:
    - port: {{ .Values.wireguard.service.port }}
      targetPort: {{ .Values.wireguard.service.port }}
      protocol: UDP
      name: wireguard
  selector:
    {{- include "wg-easy.selectorLabels" . | nindent 4 }}
